### ISSUE TITLE
Make geolocation work

### ISSUE THREAD

**Issue by daphtdazz** [daphtdazz/WebBLE#19]
Currently geolocation doesn't work, hopefully just need to add a privacy request for it so people can allow WebBLE to access the location services.

**Comment by gfwilliams** [comment]
Is there a generic 'privacy request' API you can implement? There's other stuff (webcams, audio, etc) that would usually prompt the user in a similar way, and it'd be nice to be able to implement it all in one go (as well as enabling any new stuff that comes along later).

**Comment by Gragamel** [comment]
That is not needed. The app needs to tell IOS/Android it uses location. If that is enabled stanrad java script calls just provide location. You hav similair for devices compass and sensors. Theu do not require a per app setting but just genertae a pop-up the first time you use them in a webpage.

**Comment by daphtdazz** [comment]
Thanks @Gragamel , assuming it's that easy I can add it to the next release.

**Comment by Gragamel** [comment]
Dear David,

Were you able to add the location feature to the app? I just finished the development of the WEBapp game  I made and now it is time to start communicating with my BT laser tag device for the final bits on IOS.

Regards,

**Comment by daphtdazz** [comment]
Finally I have released 1.3.1 which supports the standard geolocation APIs:

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation
