### ISSUE TITLE
console.info() does not work

### ISSUE THREAD

**Issue by daphtdazz** [daphtdazz/WebBLE#22]
And probably some other console methods.

**Comment by rajsite** [comment]
I think I ran into an issue with missing console functions for a web app I’m using with WebBLE. In this case it looks like [console.debug](https://rajsite.github.io/webvi-experiments/WebBluetooth/PuckJSBlink.html) is missing.

The webapp is actually trying to communicate with puck.js but fails at startup in webble. The app does run in Safari and only fails when actually attempting the web bluetooth connection in that browser.

**Comment by daphtdazz** [comment]
fixed in 1.3.0, and debug added too
