### ISSUE TITLE
Failed to build - WBRemoteGATTServer not found

### ISSUE THREAD

**Issue by itdir** [daphtdazz/WebBLE#41]
Hi guys,

I downloaded the latest source yesterday and tried to build it "out-of-the-box" with Xcode (11.3.1) but the build failed.  

It turns out the WBCore/Polyfill/WBRemoteGATTServer.js is missing from the project. However, there is a WBBluetoothRemoteGATTServer.js in the Polyfill directory, so I removed WBRemoteGATTServer.js from the project and added WBBluetoothRemoteGATTServer.js which then allowed the project to build successfully.

I hope this helps!

**Comment by daphtdazz** [comment]
Thanks, that was the Single Web View BLE project right? I've fixed that now.
