### ISSUE TITLE
Support pybricks

### ISSUE THREAD

**Issue by daphtdazz** [daphtdazz/WebBLE#42]

**Comment by daphtdazz** [comment]
I've got pybricks working locally with WebBLE and hopefully will be able to publish v1.7 this week with it added

**Comment by daphtdazz** [comment]
1.7.0 now released in the app store, support was added by [PR 59](https://github.com/daphtdazz/WebBLE/pull/59).

**Comment by triplef** [comment]
Unfortunately Pybricks support is very broken at the moment, to the point where it feels misleading that the app highlights Pybricks support in its description.

See #62, #64, #65, #66.

It would be great if these issues could be fixed.

**Comment by mayerwin** [comment]
Has anyone tried [Bluefy](https://apps.apple.com/us/app/bluefy-web-ble-browser/id1492822055)?
