### ISSUE TITLE
Hello, this is a great project, I want to ask android can also use your js file to encapsulate a simple browser？

### ISSUE THREAD

**Issue by TsaiYongChuan** [daphtdazz/WebBLE#43]
Because google chrome can’t meet my needs

**Comment by TsaiYongChuan** [comment]
I copied the related JS code into my Android project, and when I called the related navigator.bluetooth API, it prompted 
`Web Bluetooth is not supported on this platform. For a list of supported platforms.`

**Comment by daphtdazz** [comment]
Hi, no I'm afraid that won't work, the javascript file is coupled to the swift layer which is coupled to the iOS CoreBluetooth framework, so it won't help you much I'm afraid.
