### ISSUE TITLE
Cant select a device on iOS app

### ISSUE THREAD

**Issue by na55imK** [daphtdazz/WebBLE#46]
Hi,

the  dialogue to select a BLE device, wont show anything, as shown in the picture. It is not possible to select anything. This happens on iPhone 8 iOS 15.1 and iPadOS 15.1.

![IMG_168B01CF41CB-1](https://user-images.githubusercontent.com/92440647/145240198-45b0f4ef-12c9-41b1-b039-14cdfb034bb2.jpeg)
 
I would be happy if there is a solution to this problem.

**Comment by daphtdazz** [comment]
Hi @na55imK, did you manage to find a way around this? Were you able to connect from a different browser, and what did that look like? What device were you trying to connect to?

**Comment by na55imK** [comment]
Hi, sorry it turned out it was due to a defect Bangle.JS 2.
It works like charm now. Thank you for your response!
