### ISSUE TITLE
Not able to connect BLE device on multiple Ble Testing on Single Page

### ISSUE THREAD

**Issue by ankitnetsol** [daphtdazz/WebBLE#51]
I have to do multiple BLE device testing on a single page but it is not working. I implemented an iframe for test multiple devices on single page at the same time but it is not working but it is working for a single device. 

So anyone please give me a solution.
Thanks.

**Comment by daphtdazz** [comment]
Hey, apologies for the delay replying, but I'm afraid you're going to need to give more information. Also issues are not the best place for help with using it, they are really for well defined bugs / enhancement requests. If you still need help could you email support@greenparksoftware.co.uk with further details and I'll try and help you by email and will close this.
