### ISSUE TITLE
writeValueWithResponse / writeValueWithoutResponse

### ISSUE THREAD

**Issue by brandonros** [daphtdazz/WebBLE#56]
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValueWithResponse

https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValueWithoutResponse

https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValue = deprecated

**Comment by daphtdazz** [comment]
Implemented in [PR 59](https://github.com/daphtdazz/WebBLE/pull/59) and live on the App store as version 1.7.0
