### ISSUE TITLE
.getCharacteristic(uuid) but unable to perform .getCharacteristics() 

### ISSUE THREAD

**Issue by jiboune** [daphtdazz/WebBLE#7]
First of all, great browser thank you ! I need to use the function getCharacteristics() to get all the characteristic from a specified service. But only getCharacteristic is supported. 

- Any reason why this function isn't supported by the browser ? 
- Is the integration of this function plained to be release ? 

thanks

**Comment by daphtdazz** [comment]
No reason other than I haven't got round to it. I will see if I can in the next few weeks.

**Comment by louisn** [comment]
That would be great!  I'm very very interested.

**Comment by Thosty** [comment]
It would be very important for me that the function is supported in the next release.

My device has multiple characteristics with the same id but different properties (write, read, notify). With getCharacteristic(uuid) I only get one of these characteristics, probably the first one that matches the uuid.

**Comment by daphtdazz** [comment]
Going to try and do this in the next fortnight.
